---
- name: Install net-snmp, create users, and configure nginx
  hosts: all
  become: yes
  tasks:
    - name: Install net-snmp
      package:
        name: snmp
        state: present

    - name: Create users
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
      loop:
        - avi
        - moshe
        - yoel

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Configure nginx to run on port 8090
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen 80 default_server;'
        replace: 'listen 8090 default_server;'
       

    - name: Configure nginx IPv6 to run on port 8090
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen \[::\]:80 default_server;'
        replace: 'listen [::]:8090 default_server;'
       

    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
     